export const ROUTES = {
  root: '/',
  home: '/Home',
  aboutUs: '/AboutUs',
  accountAccess: '/AccountAcess',
  login: '/Login',
  profile: '/Profile',
  patientSignup: '/Patient/SingUpPatient',
  therapistSignup: '/Therapist/SingUpTherapist',
  passwordReset: '/RedefineWeb',
  codeAuthentication: '/CodeAuthentication',
  newPassword: '/NewPassword',
  termsOfService: '/TermsofServiceWeb',
  legalTerms: '/LegalTermsWeb',
  privacyPolicy: '/PrivacyPolicyWeb',
  faq: '/FAQWeb',
  patientProfile: '/Patient/PacientProfile',
  patientAccountInformation: '/Patient/AccountInformation',
  patientSheetsAndTests: '/Patient/SheetsAndTests',
  patientProcessesAndTreatments: '/Patient/ProcessesAndTreatments',
  patientTherapistList: '/Patient/TherapistList',
  patientTherapistProfile: '/Patient/TherapistProfileWeb',
  patientAQ10Test: '/Patient/AQ10TestWeb',
  patientAQ50Test: '/Patient/AQ50TestWeb',
  patientAQ10Result: '/Patient/AQ10ResultTest',
  patientAQ50Result: '/Patient/AQ50ResultTest',
  therapistDashboard: '/Therapist/TherapistPersonalProfile',
  therapistOurServices: '/Therapist/OurServicesWeb',
  therapistCommonPlan: '/Therapist/CommonPlanLearnMoreWeb',
  therapistCorporativePlan: '/Therapist/CorporativePlanLearnMoreWeb',
  therapistPayment: '/Therapist/Payment',
  therapistPixPayment: '/Therapist/PIXPayment',
  therapistFinishedPayment: '/Therapist/FinishedPayment',
  therapistAccountInformation: '/Therapist/AccountInformation',
  therapistPatientList: '/Therapist/PatientListPage',
  therapistMedicalRecord: '/Therapist/PatientsMedicalRecord',
  therapistReportsList: '/Therapist/ReportsList',
  therapistReports: '/Therapist/Reports',
  therapistAddNewReport: '/Therapist/AddNewReport',
  therapistScenario: '/Therapist/Scenario',
  therapistScenarioResult: '/Therapist/ScenarioResult',
  therapistCalendarHistory: '/Therapist/AppointmentsAndHistory',
};

export const dashboardPathForRole = (role?: string) => {
  if (role === 'PATIENT') return ROUTES.patientProfile;
  if (role === 'THERAPIST') return ROUTES.therapistDashboard;
  return ROUTES.home;
};
